[workspace]
members = [
        "phasor",
        "tinygl",
        "tinygl-compiler",
]

exclude = [
        "xtask",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
