name = "PhasorOpt"
uuid = "c6c9101d-ec7a-459d-93b0-91e89414bd43"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
version = "0.1.0"

[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
